import { NextRequest, NextResponse } from "next/server";
import { serverLogger } from "@/lib/server-logger";

// Force dynamic rendering - required for API routes
export const dynamic = 'force-dynamic';

export async function GET(request: NextRequest) {
  const requestId = Math.random().toString(36).substring(7);

  // Check if testing mode is enabled via header
  const testingMode = request.headers.get("x-testing-mode") === "true";

  try {
    if (testingMode) {
      serverLogger.info(
        `🧪 [API-${requestId}] Testing Mode: Using static TLD list (skipping ResellerClub API)`
      );

      // Return static TLD list for testing mode
      const staticTlds = [
        "com",
        "net",
        "org",
        "info",
        "biz",
        "co",
        "name",
        "pro",
        "mobi",
        "tel",
        "asia",
        "in",
        "co.in",
        "net.in",
        "org.in",
        "gen.in",
        "firm.in",
        "ind.in",
        "us",
        "co.uk",
        "org.uk",
        "me.uk",
        "ca",
        "com.au",
        "net.au",
        "org.au",
        "de",
        "fr",
        "it",
        "es",
        "nl",
        "be",
        "ch",
        "at",
        "se",
        "no",
        "dk",
        "fi",
        "jp",
        "co.jp",
        "kr",
        "com.cn",
        "cn",
        "com.br",
        "br",
        "mx",
        "com.mx",
        "xyz",
        "online",
        "site",
        "website",
        "store",
        "shop",
        "app",
        "dev",
        "tech",
        "digital",
        "cloud",
        "host",
        "space",
        "world",
        "global",
        "network",
        "systems",
        "solutions",
        "services",
        "business",
        "company",
        "enterprise",
        "group",
        "agency",
        "studio",
        "design",
        "media",
        "marketing",
        "consulting",
        "finance",
        "bank",
        "insurance",
        "legal",
        "education",
        "academy",
        "university",
        "school",
        "health",
        "medical",
        "doctor",
        "clinic",
        "hospital",
        "pharmacy",
        "care",
        "fitness",
        "sport",
        "golf",
        "tennis",
        "football",
        "basketball",
        "baseball",
        "music",
        "art",
        "photo",
        "video",
        "film",
        "movie",
        "tv",
        "radio",
        "news",
        "blog",
        "social",
        "community",
        "forum",
        "chat",
        "email",
        "mail",
        "web",
        "internet",
        "software",
        "games",
        "gaming",
        "play",
        "fun",
        "cool",
        "best",
        "top",
        "new",
        "now",
        "today",
        "live",
        "life",
        "love",
        "family",
        "kids",
        "baby",
        "mom",
        "dad",
        "women",
        "men",
        "fashion",
        "style",
        "beauty",
        "hair",
        "skin",
        "makeup",
        "clothing",
        "shoes",
        "jewelry",
        "watch",
        "bag",
        "handbag",
        "food",
        "restaurant",
        "cafe",
        "pizza",
        "burger",
        "coffee",
        "tea",
        "wine",
        "beer",
        "spirits",
        "cocktail",
        "bar",
        "pub",
        "club",
        "hotel",
        "travel",
        "vacation",
        "holiday",
        "trip",
        "flight",
        "car",
        "auto",
        "bike",
        "motorcycle",
        "boat",
        "yacht",
        "plane",
        "helicopter",
        "train",
        "bus",
        "taxi",
        "uber",
        "house",
        "home",
        "apartment",
        "condo",
        "villa",
        "mansion",
        "castle",
        "palace",
        "garden",
        "park",
        "beach",
        "mountain",
        "lake",
        "river",
        "ocean",
        "sea",
        "city",
        "town",
        "village",
        "country",
        "state",
        "province",
        "region",
        "area",
        "place",
        "location",
        "address",
        "street",
        "avenue",
        "road",
        "lane",
        "way",
        "money",
        "cash",
        "credit",
        "debit",
        "pay",
        "payment",
        "buy",
        "sell",
        "shop",
        "store",
        "market",
        "mall",
        "center",
        "centre",
        "plaza",
        "square",
        "circle",
      ];

      // Dedupe — the curated lists historically had `shop`/`store`
      // listed twice (once under new-gTLDs, once under the shopping
      // section), which made them appear twice in the search dropdown.
      const availableTlds = [...new Set(staticTlds)].map((tld) => ({
        name: tld,
        displayName: `.${tld}`,
        available: true,
      }));

      return NextResponse.json({
        success: true,
        tlds: availableTlds,
        requestId,
        testingMode: true,
      });
    }

    serverLogger.info(
      `🌐 [API-${requestId}] Fetching available TLDs from ResellerClub`
    );

    // Get domain pricing for a comprehensive list of TLDs
    const comprehensiveTlds = [
      // Generic TLDs
      "com",
      "net",
      "org",
      "info",
      "biz",
      "co",
      "name",
      "pro",
      "mobi",
      "tel",
      "asia",

      // Country Code TLDs
      "in",
      "co.in",
      "net.in",
      "org.in",
      "gen.in",
      "firm.in",
      "ind.in",
      "us",
      "co.uk",
      "org.uk",
      "me.uk",
      "ca",
      "com.au",
      "net.au",
      "org.au",
      "de",
      "fr",
      "it",
      "es",
      "nl",
      "be",
      "ch",
      "at",
      "se",
      "no",
      "dk",
      "fi",
      "jp",
      "co.jp",
      "kr",
      "com.cn",
      "cn",
      "com.br",
      "br",
      "mx",
      "com.mx",

      // New gTLDs
      "xyz",
      "online",
      "site",
      "website",
      "store",
      "shop",
      "app",
      "dev",
      "tech",
      "digital",
      "cloud",
      "host",
      "space",
      "world",
      "global",
      "network",
      "systems",
      "solutions",
      "services",
      "business",
      "company",
      "enterprise",
      "group",
      "agency",
      "studio",
      "design",
      "media",
      "marketing",
      "consulting",
      "finance",
      "bank",
      "insurance",
      "legal",
      "education",
      "academy",
      "university",
      "school",
      "health",
      "medical",
      "doctor",
      "clinic",
      "hospital",
      "pharmacy",
      "care",
      "fitness",
      "sport",
      "golf",
      "tennis",
      "football",
      "basketball",
      "baseball",
      "music",
      "art",
      "photo",
      "video",
      "film",
      "movie",
      "tv",
      "radio",
      "news",
      "blog",
      "social",
      "community",
      "forum",
      "chat",
      "email",
      "mail",
      "web",
      "internet",
      "software",
      "games",
      "gaming",
      "play",
      "fun",
      "cool",
      "best",
      "top",
      "new",
      "now",
      "today",
      "live",
      "life",
      "love",
      "family",
      "kids",
      "baby",
      "mom",
      "dad",
      "women",
      "men",
      "fashion",
      "style",
      "beauty",
      "hair",
      "skin",
      "makeup",
      "clothing",
      "shoes",
      "jewelry",
      "watch",
      "bag",
      "handbag",
      "food",
      "restaurant",
      "cafe",
      "pizza",
      "burger",
      "coffee",
      "tea",
      "wine",
      "beer",
      "spirits",
      "cocktail",
      "bar",
      "pub",
      "club",
      "hotel",
      "travel",
      "vacation",
      "holiday",
      "trip",
      "flight",
      "car",
      "auto",
      "bike",
      "motorcycle",
      "boat",
      "yacht",
      "plane",
      "helicopter",
      "train",
      "bus",
      "taxi",
      "uber",
      "house",
      "home",
      "apartment",
      "condo",
      "villa",
      "mansion",
      "castle",
      "palace",
      "garden",
      "park",
      "beach",
      "mountain",
      "lake",
      "river",
      "ocean",
      "sea",
      "city",
      "town",
      "village",
      "country",
      "state",
      "province",
      "region",
      "area",
      "place",
      "location",
      "address",
      "street",
      "avenue",
      "road",
      "lane",
      "way",
      "money",
      "cash",
      "credit",
      "debit",
      "pay",
      "payment",
      "buy",
      "sell",
      "shop",
      "store",
      "market",
      "mall",
      "center",
      "centre",
      "plaza",
      "square",
      "circle",
    ];

    // Return the comprehensive TLD list directly — the pricing API structure is
    // not keyed by TLD name at the top level, so we use our curated list.
    // Dedupe — same duplicate-shop/store hazard as the testing-mode branch.
    const availableTlds = [...new Set(comprehensiveTlds)].map((tld) => ({
      name: tld,
      displayName: `.${tld}`,
      available: true,
    }));

    return NextResponse.json({
      success: true,
      tlds: availableTlds,
      requestId,
    });
  } catch (error) {
    serverLogger.error(`❌ [API-${requestId}] Failed to fetch TLDs:`, {
      error: error instanceof Error ? error.message : "Unknown error",
    });

    // Fallback to common TLDs if API fails
    const fallbackTlds = [
      "com",
      "net",
      "org",
      "info",
      "biz",
      "co",
      "in",
      "co.in",
      "shop",
      "store",
      "online",
      "site",
      "website",
      "app",
      "dev",
    ].map((tld) => ({
      name: tld,
      displayName: `.${tld}`,
      available: true,
    }));

    return NextResponse.json({
      success: true,
      tlds: fallbackTlds,
      requestId,
      fallback: true,
    });
  }
}
