/**
 * DMS issues no bills (owner decision, 24 Sep 2026; built 25 Sep 2026).
 *
 * "DMS does not do its own billing anymore. Period. All bills will be
 * generated by ResellerOS itself." Every bill and every renewal is
 * ResellerOS's. So `createPrimaryInvoice` (the TI/... engine) and the legacy
 * `INV-...` number in `models/Order.ts`'s pre-save hook are gone, and a scan
 * test (tests/unit/lib/billing/no-dms-bills-scan.test.ts) fails if either
 * comes back.
 *
 * What is left is the honest record of a gap. A few paths can still take a
 * payment on DMS's own Razorpay keys — the old /cart → /checkout flow, a
 * duplicate /verify, the payment.captured webhook for such an order, an admin
 * provision with a price. ResellerOS never hears of those payments, so no bill
 * exists anywhere. Converting that into silence would be AGENTS.md §2's
 * failure; instead the order is FLAGGED (the same `invoiceFailedAt` marker the
 * admin Integration-health "Invoicing" card already lists) with a reason that
 * says what to do, and a SystemLog-visible error line is written.
 *
 * Existing invoice DATA stays: orders already carrying a TI/... or INV-...
 * number keep it and stay viewable read-only.
 */
import type mongoose from "mongoose";
import { markInvoiceCreationFailed } from "@/lib/services/orders";
import { serverLogger } from "@/lib/server-logger";

export const NO_DMS_BILL_REASON =
  "No bill issued: DMS issues no bills (owner decision, 24 Sep 2026) and this payment was taken on DMS's " +
  "Razorpay account, so ResellerOS has no record of it. ACTION: raise the bill for this payment in ResellerOS.";

/** What a customer is told where DMS used to say "your invoice is ready". */
export const CUSTOMER_BILL_NOTICE =
  "Your bill is issued by our billing system, not this panel. It will be emailed to you and shown on the Invoices page. " +
  "If it hasn't arrived within a day, please contact support.";

interface BillableOrder {
  _id: mongoose.Types.ObjectId | string;
  orderId?: string;
  amount?: number;
  orderType?: string;
}

/** A ₹0 order and a trial take no payment and never needed a bill. */
export function neededABill(order: Pick<BillableOrder, "amount" | "orderType">): boolean {
  return !!order.amount && order.amount > 0 && order.orderType !== "hosting_trial";
}

/**
 * Flag a DMS-collected payment that has no bill. Never throws: every caller is
 * past the point where the customer has paid, and a bookkeeping failure must
 * not turn a successful payment into an error (or a Razorpay webhook retry).
 */
export async function flagPaymentWithoutBill(order: BillableOrder, source: string): Promise<void> {
  if (!neededABill(order)) return;
  serverLogger.error(
    `[NO-BILL] ${source}: order ${order.orderId ?? String(order._id)} (₹${order.amount}) was paid on DMS's ` +
      `Razorpay account and has no bill. ${NO_DMS_BILL_REASON}`,
  );
  try {
    await markInvoiceCreationFailed(order._id, NO_DMS_BILL_REASON);
  } catch (err) {
    serverLogger.error(
      `[NO-BILL] ${source}: ALSO failed to flag order ${order.orderId ?? String(order._id)} — it will not show on ` +
        `Integration health: ${err instanceof Error ? err.message : String(err)}`,
    );
  }
}
